#!/usr/bin/env bash
# Generates the GitHub Release body for ai-engkit.
#
# Usage: release-body.sh <TAG> <FOOTER> [CRITICAL_COUNT]
#
#   TAG            release tag, e.g. v1.11.4
#   FOOTER         italic footer text, e.g. "Generated by GitHub Actions"
#   CRITICAL_COUNT number of critical findings from the vulnerability scan job
#                  (empty when the scan did not run)
#
# The Changes section prefers the curated docs/CHANGELOG.md section for this
# version; falls back to raw `git log` when the section does not exist yet
# (e.g. auto-tagged dependency updates that have not staged a CHANGELOG entry).
# Appends a `body` multi-line output to $GITHUB_OUTPUT.
set -euo pipefail

TAG="$1"
FOOTER="$2"
CRITICAL_COUNT="${3:-}"

VERSION_NO_V="${TAG#v}"

PREV_TAG=$(git tag --sort=-version:refname | \
  grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | \
  grep -vE '(rc|beta|alpha|dev|test|pre)' | \
  grep -v "^${TAG}$" | \
  head -1 || true)

if [ -z "$PREV_TAG" ]; then
  SINCE_TAG="first release"
else
  SINCE_TAG="${PREV_TAG}"
fi

# Prefer the curated CHANGELOG section for this version.
CHANGELOG=""
if [ -f docs/CHANGELOG.md ]; then
  CHANGELOG=$(awk -v v="$VERSION_NO_V" '
    index($0, "## [" v "] - ") == 1 {found=1; next}
    found && /^## \[/ {exit}
    found {print}
  ' docs/CHANGELOG.md || true)
fi

# Fall back to raw git log when the CHANGELOG section is missing.
if [ -z "$CHANGELOG" ]; then
  if [ -z "$PREV_TAG" ]; then
    CHANGELOG=$(git log --oneline --no-merges | head -50 || true)
  else
    CHANGELOG=$(git log "${PREV_TAG}..HEAD" --oneline --no-merges | head -50 || true)
  fi
fi

# Reflect the real scan outcome instead of a hardcoded status.
if [ -z "$CRITICAL_COUNT" ]; then
  SCAN_STATUS="⚪ Scan not run"
elif [ "$CRITICAL_COUNT" -gt 0 ] 2>/dev/null; then
  SCAN_STATUS="⚠️ ${CRITICAL_COUNT} critical finding(s) — see Security tab"
else
  SCAN_STATUS="✅ No critical vulnerabilities"
fi

{
  echo 'body<<RELEASE_BODY_EOF'
  echo '## Docker Image'
  echo ''
  echo '```bash'
  echo "docker pull ghcr.io/${GITHUB_REPOSITORY,,}:${TAG}"
  echo '```'
  echo ''
  echo '## Quick Start'
  echo ''
  echo '```bash'
  echo 'cp .env.example .env'
  echo 'docker compose up -d'
  echo '```'
  echo ''
  echo "## Changes (since ${SINCE_TAG})"
  echo ''
  echo "$CHANGELOG"
  echo ''
  echo '## Test Results'
  echo ''
  echo '| Job | Status |'
  echo '|-----|--------|'
  echo '| Integration Tests | ✅ Passed |'
  echo "| Vulnerability Scan | ${SCAN_STATUS} |"
  echo ''
  echo '---'
  echo "*${FOOTER}*"
  echo 'RELEASE_BODY_EOF'
} >> "$GITHUB_OUTPUT"
